sudo: required
services:
  - docker

before_install:
  - docker build -t joefzhu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true joefzhu/react-test npm test -- --coverage

after_success:
  - docker build -t joefzhu/multi-client ./client
  - docker build -t joefzhu/multi-nginx ./nginx
  - docker build -t joefzhu/multi-server ./server
  - docker build -t joefzhu/multi-worker ./worker

#Login to the docker CLI

  - echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --password-stdin

#Take those inmages and push them to docker hub

  - docker push joefzhu/multi-client
  - docker push joefzhu/multi-nginx
  - docker push joefzhu/multi-server
  - docker push joefzhu/multi-worker
